# application configuration
spring:
  application:
    name: INTERVIEW
  threads:
    virtual:
      enabled: true

logging:
  config: 'classpath:config/dev/log4j2.xml'
  level:
    com:
      hung:
        ming:
          repo:
            member:
              mapper: DEBUG
    org:
      springdoc: DEBUG


# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api

# api documentation
springdoc:
  api-docs:
    enabled: true
  #    path: /api-docs
  swagger-ui:
    #    display-request-duration: true
    #    path: /swagger-ui.html
    enabled: true
