# application configuration
spring:
  application:
    name: INTERVIEW
  threads:
    virtual:
      enabled: true

logging:
  config: 'classpath:config/dev/log4j2.xml'

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api


