spring:
  datasource:
    url:  jdbc:h2:file:/Users/minghungchen/Desktop/data/H2
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  pagehelper:
    propertyName: propertyValue
    reasonable: false
    defaultCount: true
